name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 5.5.5
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^4.1.0
  photo_manager: ^1.2.6+1
  provider: ^5.0.0
  video_player:
    git:
      url: https://github.com/aaronyoung001/plugins.git
      path: packages/video_player/video_player
      ref: v233
